raw_astock_output: "finance_datasource/datasource/AStock"
raw_future_output: "finance_datasource/datasource/CTPFuture"
astock_output: "finance_datasource/AStock"
future_output: "finance_datasource/CTPFuture"
tushare_token: ""
tq_username: ""
tq_psw: ""

ctp_accounts:
  - uname: "simnow"
    uid: ""
    UserID: ""
    BrokerID: ""
    AppID: ""
    AuthCode: ""
    Password: ""
    Name: ""
    FrontAddresses:
     - "tcp://180.168.146.187:10201"
     - "tcp://180.168.146.187:10202"
     - "tcp://180.168.146.187:10203"
